config/routes.rb
Rails.application.routes.draw do
  resources :haikus do
    member do
      post 'upvote'
    end
  end

  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get '/about', to: 'static#show'

  get '/connect', to: 'static#new'

  get '/users', to: 'users#index'

  root :to => "haikus#index"
end

app/models/haiku.rb
class Haiku < ActiveRecord::Base
  has_many :votes, dependent: :destroy
  has_many :upvoted_users, through: :votes, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true, length: { minimum: 1 }
  has_many :votes, dependent: :destroy
  has_many :upvoted_haikus, through: :votes, source: :haiku

  enum role: %w(default, admin)
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :haiku
  validates_uniqueness_of :haiku_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :not_found

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController

  before_action :set_haiku, only: [:show, :edit, :update, :destroy]

  def index
    @haikus = Haiku.all
  end

  def new
    @haiku = Haiku.new
  end

  def create
    @haiku = Haiku.new(haiku_params)

    if @haiku.save
      redirect_to @haiku
    else
      flash[:errors] = "You ain't done this shit right"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @haiku.update(haiku_params)
      redirect_to @haiku
    else
      flash[:errors] = "Ya dun goofed"
      render :edit
    end
  end

  def destroy
    @haiku.destroy
    redirect_to haikus_path
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def upvote
    @haiku = Haiku.find(params[:id])
    if current_user
      if @haiku.votes.create(user_id: current_user.id)
       #flash[:notice] =  "Thank you for upvoting!"
       redirect_to(haikus_path)
      else
       #flash[:notice] =  "You have already upvoted this!"
       redirect_to(haikus_path)
      end
    else
      redirect_to login_path
    end
  end

  private

  def haiku_params
    params.require(:haiku).permit(:title, :line1, :line2, :line3, :author)
  end

  def set_haiku
    @haiku = Haiku.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash.now[:errors] = "Invalid login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages.join(", ")
    end
  end

  def show
    @user = current_user
  end

  def index
    if current_user && current_user[:role] == 1
      @users = User.all
    else
      not_found
    end
  end

private

  def user_params
   params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/haikus/_form.html.erb
<%= form_for(@haiku) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>
  <%= f.text_field :line1 %>
  <%= f.text_field :line2 %>
  <%= f.text_field :line3 %>
  <%= f.text_field :author %>
  <%= f.submit %>
<% end %>

app/views/haikus/create.html.erb
<h1>Haiku</h1>

app/views/haikus/edit.html.erb
<h4>Edit this Haiku</h4>

<%= render partial: 'form' %>

app/views/haikus/index.html.erb
<div class="haiku-index">
  <% @haikus.sort_by {|haiku| haiku.votes.count }.reverse.each do |haiku| %>
    <div style="display: inline-block;">
     <%= button_to "\u2B06", upvote_haiku_path(haiku), method: :post, class: "octicon octicon-arrow-small-up" %>
    </div>
    <span style="text-color:#55ACEE; font-size:175%;">
      <%= haiku.votes.count %>
     <%= link_to haiku.title, haiku_path(haiku) %>
    </span>
  <% if current_user && current_user[:role] == 1 %>
   <%= link_to "New Haiku", new_haiku_path %>
   <%= link_to "Edit", edit_haiku_path(haiku) %>
   <%= link_to "Delete", haiku_path(haiku), method: :delete%>
  <% end %>
   <br>
  <% end %>
</div>

app/views/haikus/new.html.erb
<h3>Submit a new tweetHaiku</h3>

<%= render partial: 'form' %>

app/views/haikus/show.html.erb
<h3 class="tweethaiku"><%= @haiku.title %></h3>

<h5><%= @haiku.line1 %></h5>
<h5> <%= @haiku.line2 %></h5>
<h5> <%= @haiku.line3 %></h5> <br>
<h6 id="italic"><%= @haiku.author %></h6>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tweetHaiku</title>
  <link href='http://fonts.googleapis.com/css?family=Bad+Script|Marck+Script|Seaweed+Script|Dancing+Script' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  <link rel="stylesheet" href="/octicons/octicons.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<a href="/"><h1 class="tweethaiku">tweetHaiku</h1></a>

  <h5>
    <ul class="navbar" class="center-align">
      <li class="nav-item"><a href="/about">About</a></li>
      <li class="nav-item"><a href="/connect">Connect</a></li>

      <% unless current_user %>
        <li class="nav-item"><a href="/login">Login</a></li>
      <% else %>
        <li class="nav-item">
        <%= link_to 'logout', logout_path, :method => :delete %>
       </li>
      <% end %>

      <li class="nav-item"><a href="/users/new">Signup</a></li>
    </ul>
  </h5>

  <div class="container">
    <% flash.each do |name, msg| %>
     <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>
      <div class="push"></div>
  </div>
  <br>
  <br>
  <div class="footer">
    <h4><span class="mega-octicon octicon-pencil"></span>  with <span class="octicon-mega octicon-heart"></span> by <a class="lk" style="color:#55ACEE;" href="http://lev.io">{l/k}</a></h4>
  </div>

</body>
</html>

app/views/users/index.html.erb
<h1>ADMIN AREA</h1>
  <ul>
    <% @users.each do |user| %>
      <li><%= user.username %></li> <br>
    <% end %>
  </ul>

app/views/users/new.html.erb
<div class="container" class="pure-form">
<%= form_for(@user) do |f| %>

  <%= f.text_field :username, placeholder: "username" %> <br>
  <%= f.password_field :password, placeholder: "password" %> <br>

  <%= f.submit "Signup", class: "octicon octicon-arrow-down" %>
<% end %>
</div>